import Link from 'next/link';
import { ArrowRight, CalendarDays, Package, Users, WalletCards } from 'lucide-react';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { ClinicFinancialData } from '@/server/financeiro/clinica';
import { ClinicHubHeader } from './clinic-hub-header';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });

export function ClinicOverviewPanel({ basePath, nomeClinica, title, hasPersonalFinance, financeiro, mensagem }: { basePath: '/dashboard/meu-consultorio' | '/consultorio'; nomeClinica: string; title: 'Meu Consultório' | 'Minha Clínica'; hasPersonalFinance: boolean; financeiro: ClinicFinancialData | null; mensagem?: string }): React.JSX.Element {
  return <div className="space-y-8"><ClinicHubHeader active="overview" basePath={basePath} nomeClinica={nomeClinica} title={title} hasPersonalFinance={hasPersonalFinance} /><section><h2 className="font-heading text-2xl text-text-primary">Visão geral</h2><p className="mt-1 text-sm text-text-secondary">Acompanhe o que pede decisão na sua clínica.</p></section>{financeiro ? <section><div className="flex items-end justify-between gap-4"><div><h2 className="font-heading text-2xl text-text-primary">Resultado da unidade</h2><p className="mt-1 text-sm text-text-secondary">Caixa confirmado e valores que ainda dependem de recebimento.</p></div><Link href={`${basePath}/financeiro-clinica`} className="hidden items-center gap-1 text-sm font-medium text-teal hover:text-teal-ink sm:inline-flex">Abrir financeiro <ArrowRight className="size-4" /></Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Recebido pela clínica" value={money.format(financeiro.recebido)} detail="Recebimentos confirmados" /><Summary label="A receber" value={money.format(financeiro.aReceber)} detail="Cobranças ativas" /><Summary label="Despesas registradas" value={money.format(financeiro.despesas)} detail="Fixas e variáveis lançadas" /><Summary label="Saldo de caixa" value={money.format(financeiro.saldoCaixa)} detail="Entradas confirmadas menos despesas" /></div></section> : <section role="status" className="rounded-xl border border-border bg-surface p-5 text-sm text-text-secondary">{mensagem ?? 'O resumo financeiro da clínica estará disponível após a configuração inicial.'}</section>}<section><h2 className="font-heading text-2xl text-text-primary">Financeiro e operação</h2><p className="mt-1 text-sm text-text-secondary">Leituras rápidas para decidir onde agir primeiro.</p><div className="mt-4 grid gap-4 lg:grid-cols-3"><Destination href={`${basePath}/financeiro-clinica`} icon={WalletCards} title="Financeiro da clínica" description="Caixa, previsão, margem estimada e recebimentos por profissional." /><Destination href={`${basePath}/equipe`} icon={Users} title="Minha equipe" description="Acesse convites, funções e permissões da operação." /><Destination href={`${basePath}/estoque`} icon={Package} title="Estoque" description="Materiais, kits e alertas de reposição da clínica." /></div></section><section className="rounded-xl border border-border bg-surface-alt/50 p-5"><div className="flex gap-3"><CalendarDays className="mt-0.5 size-5 shrink-0 text-teal" /><div><h2 className="font-medium text-text-primary">Pendências de pacientes</h2><p className="mt-1 text-sm text-text-secondary">Remarcação e reativação continuarão em Pacientes → Pendências, onde secretaria e assistência podem agir sem acessar a gestão financeira.</p><Link className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-teal hover:text-teal-ink" href="/dashboard/pacientes">Abrir pacientes <ArrowRight className="size-4" /></Link></div></div></section></div>;
}

function Summary({ label, value, detail }: { label: string; value: string; detail: string }): React.JSX.Element { return <Card><CardContent className="pt-4"><p className="text-xs text-text-secondary">{label}</p><p className="mt-2 font-mono text-lg font-semibold text-text-primary">{value}</p><p className="mt-1 text-xs text-text-secondary">{detail}</p></CardContent></Card>; }
function Destination({ href, icon: Icon, title, description }: { href: string; icon: typeof WalletCards; title: string; description: string }): React.JSX.Element { return <Link href={href} className="group"><Card className="h-full transition-colors hover:border-teal/40"><CardHeader><Icon className="size-5 text-teal" /><CardTitle className="mt-2 font-heading text-xl">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent><span className="inline-flex items-center gap-1 text-sm font-medium text-teal">Abrir <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" /></span></CardContent></Card></Link>; }
