'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { AlertTriangle, CalendarClock, Landmark, ReceiptText, WalletCards } from 'lucide-react';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { ClinicFinancialData } from '@/server/financeiro/clinica';
import type { ClinicRepassesData } from '@/server/financeiro/repasses';
import { ClinicTransactionActions } from './clinic-transaction-actions';
import { ClinicRepassePanel } from './clinic-repasse-panel';

type DetailTab = 'resumo' | 'cobrancas' | 'custos' | 'equipe' | 'extrato';
type Props = { basePath: '/dashboard/meu-consultorio' | '/consultorio'; data: ClinicFinancialData | null; canRegisterIncome: boolean; canRegisterCost: boolean; repasses: ClinicRepassesData | null; canManageRepasses: boolean; professionals: { id: string; nome: string }[]; operationalOnly?: boolean; mensagem?: string };
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const shortDate = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' });
const formatMoney = (value: number): string => money.format(value);
const percentage = (value: number | null): string => value == null ? '—' : `${value.toFixed(1).replace('.', ',')}%`;

function conclusion(data: ClinicFinancialData): string {
  if (data.movimentoLiquido < 0) return `A clínica fechou ${formatMoney(Math.abs(data.movimentoLiquido))} abaixo do ponto de equilíbrio.`;
  return data.vencido > 0 ? `A clínica gerou ${formatMoney(data.movimentoLiquido)} no mês — a cobrança pede atenção.` : `A clínica gerou ${formatMoney(data.movimentoLiquido)} no mês.`;
}

export function ClinicFinancePanelV2({ basePath, data, canRegisterIncome, canRegisterCost, repasses, canManageRepasses, professionals, operationalOnly = false, mensagem }: Props): React.JSX.Element {
  const [detail, setDetail] = useState<DetailTab>('resumo');
  const plannedRepasses = useMemo(() => repasses?.repasses.filter((item) => item.status === 'previsto').reduce((total, item) => total + item.valor, 0) ?? 0, [repasses]);
  if (operationalOnly) return <section className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Operação financeira</p><div className="mt-2 flex flex-wrap items-end justify-between gap-5"><div><h2 className="font-heading text-3xl font-normal text-text-primary">Registrar fato financeiro</h2><p className="mt-2 max-w-xl text-sm text-text-secondary">Recebimentos de pacientes ficam no orçamento. Aqui entram somente custo pago ou receita realmente avulsa.</p></div><ClinicTransactionActions canRegisterIncome={canRegisterIncome} canRegisterCost={canRegisterCost} professionals={professionals} /></div></section>;
  if (!data) return <section role="alert" className="rounded-2xl border border-coral/30 bg-coral-pale p-5 text-sm text-text-primary"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-coral-ink" /><p>{mensagem ?? 'O financeiro da clínica está indisponível agora. Os valores não foram substituídos por zero.'}</p></div></section>;
  const plannedExpenses = data.despesasFixasPrevistas + plannedRepasses;
  const variation = data.aReceber - plannedExpenses;
  const tabs: { id: DetailTab; label: string }[] = [{ id: 'resumo', label: 'Resumo' }, { id: 'cobrancas', label: 'Cobranças' }, { id: 'custos', label: 'Custos' }, { id: 'equipe', label: 'Equipe' }, { id: 'extrato', label: 'Extrato' }];
  return <div className="space-y-10">
    <section className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><div className="flex flex-col gap-6 xl:flex-row xl:items-start xl:justify-between"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Decisão financeira</p><h2 className="mt-2 font-heading text-3xl font-normal tracking-tight text-text-primary sm:text-4xl">{conclusion(data)}</h2><p className="mt-3 text-sm text-text-secondary">Realizado primeiro. Previsão, custos e extrato ficam no detalhamento.</p></div><ClinicTransactionActions canRegisterIncome={canRegisterIncome} canRegisterCost={canRegisterCost} professionals={professionals} /></div><div className="mt-7 grid gap-5 border-t border-border pt-6 sm:grid-cols-2 xl:grid-cols-4"><SnapshotMetric label="Recebido" value={formatMoney(data.recebido)} detail="confirmado" /><SnapshotMetric label="Saídas pagas" value={formatMoney(data.despesas)} detail="custos + repasses" /><SnapshotMetric label="Resultado de caixa" value={formatMoney(data.movimentoLiquido)} detail="não é lucro contábil" tone={data.movimentoLiquido >= 0 ? 'positive' : 'negative'} /><SnapshotMetric label="Margem de caixa" value={data.baseDeCustosValidada ? percentage(data.margemOperacional) : '—'} detail={data.baseDeCustosValidada ? 'base validada' : 'sem base de custos'} /></div></section>
    <section className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-warning-ink">Próximos 30 dias</p><h2 className="mt-1 font-heading text-2xl font-normal text-text-primary sm:text-[28px]">Variação prevista</h2><div className="mt-6 grid gap-5 border-y border-border py-5 sm:grid-cols-3"><SnapshotMetric label="A receber" value={`+ ${formatMoney(data.aReceber)}`} detail="cobranças pendentes" tone="positive" /><SnapshotMetric label="Contas + repasses" value={`− ${formatMoney(plannedExpenses)}`} detail="obrigações registradas" tone="negative" /><SnapshotMetric label="Variação" value={`${variation >= 0 ? '+ ' : '− '}${formatMoney(Math.abs(variation))}`} detail="não é saldo futuro" tone={variation >= 0 ? 'positive' : 'negative'} /></div><p className="mt-4 text-sm text-text-secondary">Sem saldo bancário conectado, a previsão mostra somente a variação esperada — não inventa saldo final.</p><div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-dashed border-border bg-surface-alt/45 p-4"><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-surface text-text-secondary"><Landmark className="size-4" aria-hidden="true" /></span><div><p className="font-semibold text-text-primary">Saldo e fôlego de caixa</p><p className="mt-1 text-sm text-text-secondary">Disponíveis quando uma conta for conectada pelo Open Finance. Não existe atualização manual de saldo.</p></div></div><span className="rounded-full border border-border px-3 py-1.5 text-xs font-semibold text-text-secondary">Aguardando integração</span></div></section>
    <section><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Detalhes</p><h2 className="mt-1 font-heading text-2xl font-normal text-text-primary sm:text-[28px]">Entenda o motivo</h2><div className="mt-4 flex gap-1 overflow-x-auto border-b border-border pb-2" role="tablist" aria-label="Detalhes financeiros">{tabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={detail === tab.id} onClick={() => setDetail(tab.id)} className={detail === tab.id ? 'min-h-10 shrink-0 rounded-lg bg-surface-alt px-3 text-sm font-semibold text-text-primary' : 'min-h-10 shrink-0 rounded-lg px-3 text-sm font-semibold text-text-secondary hover:bg-surface-alt/70 hover:text-text-primary'}>{tab.label}</button>)}</div><div className="mt-4">{detail === 'resumo' && <Summary data={data} />}{detail === 'cobrancas' && <Collections data={data} />}{detail === 'custos' && <Costs basePath={basePath} data={data} />}{detail === 'equipe' && <Team data={data} repasses={repasses} canManageRepasses={canManageRepasses} />}{detail === 'extrato' && <Statement data={data} />}</div></section>
  </div>;
}

function SnapshotMetric({ label, value, detail, tone = 'default' }: { label: string; value: string; detail: string; tone?: 'default' | 'positive' | 'negative' }): React.JSX.Element { const color = tone === 'positive' ? 'text-teal-ink' : tone === 'negative' ? 'text-coral-ink' : 'text-text-primary'; return <div><p className="text-xs font-semibold text-text-secondary">{label}</p><p className={`mt-2 font-mono text-2xl font-semibold ${color}`}>{value}</p><p className="mt-1 text-xs text-text-muted">{detail}</p></div>; }
function Summary({ data }: { data: ClinicFinancialData }): React.JSX.Element { return <div className="grid gap-4 md:grid-cols-3"><DetailCard icon={WalletCards} label="Resultado de caixa" value={formatMoney(data.movimentoLiquido)} detail="entradas confirmadas menos saídas pagas" /><DetailCard icon={ReceiptText} label="A receber" value={formatMoney(data.aReceber)} detail={data.vencido > 0 ? `${formatMoney(data.vencido)} já vencidos` : 'sem cobrança vencida'} /><DetailCard icon={CalendarClock} label="Custos fixos ativos" value={formatMoney(data.despesasFixasPrevistas)} detail="projeção mensal registrada" /></div>; }
function Collections({ data }: { data: ClinicFinancialData }): React.JSX.Element { return <Card><CardHeader><CardTitle className="font-heading text-2xl font-normal">Cobranças pendentes</CardTitle><CardDescription>Valores vencidos não somem dentro do total a receber.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><SnapshotMetric label="Total a receber" value={formatMoney(data.aReceber)} detail="todas as cobranças pendentes" /><SnapshotMetric label="Vencido" value={formatMoney(data.vencido)} detail={data.vencido > 0 ? 'prioridade operacional' : 'nenhuma cobrança vencida'} tone={data.vencido > 0 ? 'negative' : 'positive'} /></CardContent></Card>; }
function Costs({ basePath, data }: { basePath: Props['basePath']; data: ClinicFinancialData }): React.JSX.Element { return <Card><CardHeader><CardTitle className="font-heading text-2xl font-normal">Custos fixos e pontuais</CardTitle><CardDescription>Conta recorrente é previsão; somente pagamento confirmado entra na saída do mês.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="grid gap-4 sm:grid-cols-2"><SnapshotMetric label="Custos fixos ativos" value={formatMoney(data.despesasFixasPrevistas)} detail={`${data.recorrencias.filter((item) => item.ativo).length} regra(s) recorrente(s)`} /><SnapshotMetric label="Pago no período" value={formatMoney(data.despesas)} detail="custos + repasses efetivados" /></div>{data.podeGerirCustos && <Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/80" href={`${basePath}/financeiro-clinica/custos`}><CalendarClock className="size-4" />Gerenciar custos</Link>}</CardContent></Card>; }
function Team({ data, repasses, canManageRepasses }: { data: ClinicFinancialData; repasses: ClinicRepassesData | null; canManageRepasses: boolean }): React.JSX.Element { return <div className="space-y-6"><Card className="overflow-hidden"><CardHeader><CardTitle className="font-heading text-2xl font-normal">Leitura da equipe</CardTitle><CardDescription>Produção aprovada e dinheiro recebido são fatos diferentes.</CardDescription></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-surface-alt text-xs uppercase tracking-wider text-text-secondary"><tr><th className="px-5 py-3 font-semibold">Profissional</th><th className="px-5 py-3 text-right font-semibold">Produção aprovada</th><th className="px-5 py-3 text-right font-semibold">Atendimentos</th><th className="px-5 py-3 text-right font-semibold">Recebido</th></tr></thead><tbody>{data.profissionais.length === 0 ? <tr><td className="px-5 py-6 text-text-secondary" colSpan={4}>Ainda não há profissionais clínicos ativos nesta unidade.</td></tr> : data.profissionais.map((person) => <tr className="border-t border-border" key={person.dentistaId}><td className="px-5 py-4 font-semibold text-text-primary">{person.nome}<p className="mt-1 text-xs font-normal text-text-secondary">{person.horasAtendidas.toLocaleString('pt-BR', { maximumFractionDigits: 1 })} h atendidas</p></td><td className="px-5 py-4 text-right font-mono">{formatMoney(person.producaoAprovada)}</td><td className="px-5 py-4 text-right font-mono">{person.atendimentosRealizados}</td><td className="px-5 py-4 text-right font-mono text-teal-ink">{formatMoney(person.recebidoVinculado)}</td></tr>)}</tbody></table></CardContent></Card><ClinicRepassePanel data={repasses} canManage={canManageRepasses} mes={data.mes} /></div>; }
const methodLabel: Record<NonNullable<ClinicFinancialData['extrato'][number]['forma']>, string> = { pix: 'PIX', dinheiro: 'Dinheiro', transferencia: 'Transferência', cartao_credito: 'Cartão crédito', cartao_debito: 'Cartão débito', boleto: 'Boleto', outro: 'Outro' };
function Statement({ data }: { data: ClinicFinancialData }): React.JSX.Element { const [method, setMethod] = useState<'todos' | NonNullable<ClinicFinancialData['extrato'][number]['forma']>>('todos'); const receivedMethods = data.recebidoPorModalidade.filter((item) => item.valor > 0); const entries = method === 'todos' ? data.extrato : data.extrato.filter((item) => item.forma === method); return <Card><CardHeader><CardTitle className="font-heading text-2xl font-normal">Extrato da clínica</CardTitle><CardDescription>Fatos confirmados no período. Filtre os recebimentos pela forma de pagamento.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex flex-wrap gap-2" aria-label="Filtrar recebimentos por forma"><button type="button" onClick={() => setMethod('todos')} className={method === 'todos' ? 'min-h-9 rounded-lg bg-teal px-3 text-xs font-semibold text-white' : 'min-h-9 rounded-lg border border-border px-3 text-xs font-semibold text-text-secondary hover:bg-surface-alt'}>Todos</button>{receivedMethods.map((item) => <button key={item.forma} type="button" onClick={() => setMethod(item.forma)} className={method === item.forma ? 'min-h-9 rounded-lg bg-teal px-3 text-xs font-semibold text-white' : 'min-h-9 rounded-lg border border-border px-3 text-xs font-semibold text-text-secondary hover:bg-surface-alt'}>{methodLabel[item.forma]} · {formatMoney(item.valor)}</button>)}</div>{entries.length === 0 ? <p className="py-3 text-sm text-text-secondary">Nenhum lançamento confirmado para este filtro.</p> : entries.map((item) => <div key={`${item.tipo}-${item.id}`} className="flex items-center justify-between gap-4 border-b border-border pb-3 last:border-0 last:pb-0"><div><p className="font-semibold text-text-primary">{item.descricao}</p><p className="mt-1 text-xs text-text-secondary">{item.tipo === 'despesa' ? 'Despesa' : item.tipo === 'receita_manual' ? 'Receita manual' : 'Recebimento'}{item.forma ? ` · ${methodLabel[item.forma]}` : ''} · {shortDate.format(new Date(`${item.data}T12:00:00`))}</p></div><p className={item.valor < 0 ? 'font-mono text-coral-ink' : 'font-mono text-teal-ink'}>{item.valor < 0 ? '− ' : '+ '}{formatMoney(Math.abs(item.valor))}</p></div>)}</CardContent></Card>; }
function DetailCard({ icon: Icon, label, value, detail }: { icon: typeof WalletCards; label: string; value: string; detail: string }): React.JSX.Element { return <Card><CardContent className="p-5"><Icon className="size-4 text-teal" /><p className="mt-4 text-xs font-semibold text-text-secondary">{label}</p><p className="mt-2 font-mono text-xl font-semibold text-text-primary">{value}</p><p className="mt-2 text-xs text-text-secondary">{detail}</p></CardContent></Card>; }
