import { AlertTriangle, BanknoteArrowDown, CircleDollarSign, FileCheck2, ReceiptText } from 'lucide-react';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { ManagedPersonalData } from '@/server/financeiro/repasses';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const formatMoney = (value: number): string => money.format(value);

function agreementLabel(data: ManagedPersonalData['acordo']): string {
  if (!data) return 'Acordo pendente';
  if (data.modalidade === 'percentual_recebido') return `${data.percentual?.toLocaleString('pt-BR')}% dos recebimentos confirmados`;
  if (data.modalidade === 'diaria') return `${formatMoney(data.valorFixo ?? 0)} por diária registrada`;
  return `${formatMoney(data.valorFixo ?? 0)} por mês`;
}

export function ManagedPersonalFinancePanel({ data, mensagem }: { data: ManagedPersonalData | null; mensagem?: string }): React.JSX.Element {
  if (!data) return <section role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-foreground"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-destructive" /><p>{mensagem ?? 'O seu financeiro está indisponível agora. Os valores não foram substituídos por zero.'}</p></div></section>;
  return <div className="space-y-10">
    <section className="rounded-[18px] border border-teal/30 bg-teal-pale p-5 sm:p-7">
      <div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-teal"><CircleDollarSign className="size-4" />Meu financeiro</p><h2 className="mt-3 font-heading text-3xl font-normal text-foreground">Seu ganho na clínica</h2><p className="mt-2 max-w-xl text-sm text-muted-foreground">O recebimento do paciente pertence ao caixa da clínica. Aqui entram produção, valores vinculados e seus repasses.</p></div><div className="grid grid-cols-2 gap-x-8 gap-y-5"><Inline label="Previsto" value={formatMoney(data.repassePrevisto)} /><Inline label="Pago" value={formatMoney(data.repassePago)} /><Inline label="Produção" value={formatMoney(data.producaoAprovada)} /><Inline label="Recebido vinculado" value={formatMoney(data.pagamentosVinculados)} /></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<FileCheck2 className="size-4" />} label="Produção aprovada" value={formatMoney(data.producaoAprovada)} detail="Orçamentos aprovados no período" /><Metric icon={<ReceiptText className="size-4" />} label="Recebido vinculado" value={formatMoney(data.pagamentosVinculados)} detail="Pagamentos confirmados da clínica" /><Metric icon={<BanknoteArrowDown className="size-4" />} label="Repasse previsto" value={formatMoney(data.repassePrevisto)} detail="Ainda não saiu do caixa" tone="teal" /><Metric icon={<CircleDollarSign className="size-4" />} label="Repasse pago" value={formatMoney(data.repassePago)} detail="Pagamento já confirmado" tone="teal" /></section>
    <section className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><Card><CardHeader><CardTitle className="font-heading text-2xl font-normal">Acordo vigente</CardTitle><CardDescription>A regra usada para criar os seus próximos repasses.</CardDescription></CardHeader><CardContent>{data.acordo ? <div className="space-y-3"><p className="text-lg font-semibold text-foreground">{agreementLabel(data.acordo)}</p><p className="text-sm text-muted-foreground">Vigente desde {new Intl.DateTimeFormat('pt-BR').format(new Date(data.acordo.vigenteDesde + 'T12:00:00'))}{data.acordo.vigenteAte ? ` até ${new Intl.DateTimeFormat('pt-BR').format(new Date(data.acordo.vigenteAte + 'T12:00:00'))}` : ''}.</p></div> : <p className="text-sm text-muted-foreground">O proprietário ou gestor ainda não configurou seu acordo. Nenhum valor é calculado até isso acontecer.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="font-heading text-2xl font-normal">Histórico de repasses</CardTitle><CardDescription>Previsto continua separado do que já foi pago.</CardDescription></CardHeader><CardContent className="space-y-3">{data.repasses.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum repasse neste período.</p> : data.repasses.map((repasse) => <div key={repasse.id} className="flex items-center justify-between gap-4 border-b border-border pb-3 last:border-0 last:pb-0"><div><p className="font-semibold text-foreground">{originLabel(repasse.origem)}</p><p className="mt-1 text-xs text-muted-foreground">Competência {new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date(repasse.competencia + 'T12:00:00'))}</p></div><div className="text-right"><p className="font-mono font-semibold text-foreground">{formatMoney(repasse.valor)}</p><p className={repasse.status === 'pago' ? 'mt-1 text-xs font-semibold text-teal' : repasse.status === 'previsto' ? 'mt-1 text-xs font-semibold text-amber-600 dark:text-amber-400' : 'mt-1 text-xs text-muted-foreground'}>{repasse.status === 'pago' ? 'Pago' : repasse.status === 'previsto' ? 'Previsto' : 'Cancelado'}</p></div></div>)}</CardContent></Card></section>
  </div>;
}
function Inline({ label, value }: { label: string; value: string }): React.JSX.Element { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold text-foreground">{value}</p></div>; }
function Metric({ icon, label, value, detail, tone = 'default' }: { icon: React.ReactNode; label: string; value: string; detail: string; tone?: 'default' | 'teal' }): React.JSX.Element { return <Card><CardContent className="p-5"><p className="flex items-center gap-2 text-xs font-semibold text-muted-foreground">{icon}{label}</p><p className={tone === 'teal' ? 'mt-3 font-mono text-xl font-semibold text-teal' : 'mt-3 font-mono text-xl font-semibold text-foreground'}>{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></CardContent></Card>; }
function originLabel(origin: 'percentual' | 'diaria' | 'mensal'): string { return origin === 'percentual' ? 'Repasse percentual' : origin === 'diaria' ? 'Diária' : 'Mensal fixo'; }
