import { AlertTriangle, CalendarDays, Clock3, ReceiptText, WalletCards } from 'lucide-react';

import { Card, CardContent } from '@/components/ui/card';
import type { ManagedPersonalData } from '@/server/financeiro/repasses';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const formatMoney = (value: number): string => money.format(value);

export function ManagedPersonalFinancePanel({ data, mensagem }: { data: ManagedPersonalData | null; mensagem?: string }): React.JSX.Element {
  if (!data) return <section role="alert" className="rounded-2xl border border-coral/30 bg-coral-pale p-5 text-sm text-text-primary"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-coral-ink" /><p>{mensagem ?? 'O seu financeiro está indisponível agora. Os valores não foram substituídos por zero.'}</p></div></section>;
  const margin = data.entradasPessoais > 0 ? (data.resultadoPessoal / data.entradasPessoais) * 100 : null;
  const hourCost = data.custoPorHoraClinica == null ? '—' : `${formatMoney(data.custoPorHoraClinica)}/h`;
  return <div className="space-y-10">
    <section><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Modelo do consultório</p><div className="mt-3 flex flex-wrap gap-2 rounded-xl border border-border bg-surface p-2"><span className="rounded-lg px-4 py-2 text-sm font-semibold text-text-secondary">Colaborativo</span><span className="rounded-lg bg-surface-alt px-4 py-2 text-sm font-semibold text-text-primary">Clínica gerida</span></div></section>
    <section className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Seu consultório como empresa</p><h2 className="mt-2 font-heading text-3xl font-normal tracking-tight text-text-primary sm:text-4xl">Você recebeu {formatMoney(data.entradasPessoais)} neste período.</h2><p className="mt-3 max-w-2xl text-sm text-text-secondary">Aqui entram apenas receitas e despesas que pertencem a você. O caixa da clínica continua separado.</p><div className="mt-7 grid gap-5 border-t border-border pt-6 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Entrou" value={formatMoney(data.entradasPessoais)} detail="resultado pessoal" /><Metric label="Gastou" value={formatMoney(data.custosProfissionais)} detail="custos próprios pagos" /><Metric label="Resultado de caixa" value={formatMoney(data.resultadoPessoal)} detail="sobrou no período" tone={data.resultadoPessoal >= 0 ? 'positive' : 'negative'} /><Metric label="Margem" value={margin == null ? '—' : `${margin.toFixed(1).replace('.', ',')}%`} detail="sobre o que entrou" /></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.12fr_0.88fr]"><div className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Hora clínica</p><h2 className="mt-1 font-heading text-2xl font-normal text-text-primary">Quanto custou cada hora atendida</h2><p className="mt-5 font-mono text-4xl font-semibold text-text-primary">{hourCost}</p><p className="mt-2 text-sm text-text-secondary">Custos pagos ÷ {data.horasAtendidas.toLocaleString('pt-BR', { maximumFractionDigits: 1 })} horas concluídas.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><MiniMetric icon={Clock3} label="Horas atendidas" value={`${data.horasAtendidas.toLocaleString('pt-BR', { maximumFractionDigits: 1 })} h`} /><MiniMetric icon={CalendarDays} label="Ocupação" value={data.ocupacaoRealizada == null ? '—' : `${data.ocupacaoRealizada.toLocaleString('pt-BR')}%`} /><MiniMetric icon={ReceiptText} label="Ticket aprovado" value={data.ticketAprovado == null ? '—' : formatMoney(data.ticketAprovado)} /><MiniMetric icon={WalletCards} label="A receber" value={formatMoney(data.repassePrevisto)} /></div></section>
    <section className="rounded-2xl border border-border bg-surface p-5 sm:p-7"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal">Repasses</p><h2 className="mt-1 font-heading text-2xl font-normal text-text-primary">O que a clínica confirmou para você</h2><div className="mt-6 grid gap-5 border-t border-border pt-5 sm:grid-cols-2"><Metric label="Repasse previsto" value={formatMoney(data.repassePrevisto)} detail="obrigação da clínica" /><Metric label="Repasse pago" value={formatMoney(data.repassePago)} detail="já virou entrada pessoal" tone="positive" /></div></section>
  </div>;
}

function Metric({ label, value, detail, tone = 'default' }: { label: string; value: string; detail: string; tone?: 'default' | 'positive' | 'negative' }): React.JSX.Element { const color = tone === 'positive' ? 'text-teal-ink' : tone === 'negative' ? 'text-coral-ink' : 'text-text-primary'; return <div><p className="text-xs font-semibold text-text-secondary">{label}</p><p className={`mt-2 font-mono text-2xl font-semibold ${color}`}>{value}</p><p className="mt-1 text-xs text-text-muted">{detail}</p></div>; }
function MiniMetric({ icon: Icon, label, value }: { icon: typeof WalletCards; label: string; value: string }): React.JSX.Element { return <Card className="py-0"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-9 items-center justify-center rounded-lg bg-surface-alt text-teal"><Icon className="size-4" /></span><div><p className="text-xs font-semibold text-text-secondary">{label}</p><p className="mt-1 font-mono text-lg font-semibold text-text-primary">{value}</p></div></CardContent></Card>; }
