export const ErrorCode = {
  // Auth
  UNAUTHENTICATED:        'UNAUTHENTICATED',
  SESSION_EXPIRED:        'SESSION_EXPIRED',
  FIRST_ACCESS_REQUIRED:  'FIRST_ACCESS_REQUIRED',
  EMAIL_ALREADY_EXISTS:   'EMAIL_ALREADY_EXISTS',

  // Autorização
  INSUFFICIENT_PERMISSION:   'INSUFFICIENT_PERMISSION',
  INVALID_INVITE:            'INVALID_INVITE',
  INVITE_EXPIRED:            'INVITE_EXPIRED',
  INVITE_ALREADY_ACCEPTED:   'INVITE_ALREADY_ACCEPTED',
  INVITE_LIMIT_REACHED:      'INVITE_LIMIT_REACHED',
  SELF_REMOVAL_BLOCKED:      'SELF_REMOVAL_BLOCKED',
  LAST_ADMIN_BLOCKED:        'LAST_ADMIN_BLOCKED',

  // Validação
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND:        'NOT_FOUND',
  CONFLICT:         'CONFLICT',

  // Webhooks
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',

  // Serviços externos
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_RESPONSE_INVALID:     'AI_RESPONSE_INVALID',
  UPLOAD_FAILED:           'UPLOAD_FAILED',
  EXTERNAL_SERVICE_ERROR:  'EXTERNAL_SERVICE_ERROR',

  // Financeiro
  INVALID_FINANCE_SCOPE: 'INVALID_FINANCE_SCOPE',

  // Genérico
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNKNOWN_ERROR:  'UNKNOWN_ERROR',
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
