-- R-140e2: leituras mínimas para a seção de materiais, sem expor estoque fora do escopo.
create function private.listar_kits_estoque(p_entrada jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_clinica uuid:=private.estoque_uuid(p_entrada->>'clinicaIdEsperada'); v_contexto jsonb; v_titular text:=coalesce(p_entrada#>>'{titular,tipo}',''); v_dentista uuid:=private.estoque_uuid(p_entrada#>>'{titular,dentistaId}');
begin
  if jsonb_typeof(p_entrada)<>'object' or not private.estoque_chaves_exatas(p_entrada,array['clinicaIdEsperada','titular']) or v_clinica is null then return jsonb_build_object('ok',false,'codigo','INVALIDO','mensagem','Consulta de kits inválida.'); end if;
  v_contexto:=private.estoque_contexto_travado(v_clinica); if (v_contexto->>'ok')::boolean is not true then return v_contexto; end if;
  if not private.estoque_tem_acao(v_contexto,v_titular,v_dentista,'estoque.ler') then return jsonb_build_object('ok',false,'codigo','SEM_ACESSO','mensagem','Sem acesso aos kits.'); end if;
  return jsonb_build_object('ok',true,'data',jsonb_build_object('kits',coalesce((select jsonb_agg(jsonb_build_object('kitId',k.id::text,'kitVersaoId',(select kv.id::text from public.estoque_kit_versoes kv where kv.clinica_id=k.clinica_id and kv.kit_id=k.id and kv.versao=k.versao_atual),'nome',k.nome,'versao',k.versao_atual,'componentes',coalesce((select jsonb_agg(jsonb_build_object('itemId',c.item_id::text,'nome',c.nome_snapshot,'unidade',c.unidade_snapshot,'quantidade',private.estoque_decimal_text(c.quantidade_base)) order by c.nome_snapshot) from public.estoque_kit_componentes c join public.estoque_kit_versoes kv on kv.clinica_id=c.clinica_id and kv.id=c.kit_versao_id where kv.clinica_id=k.clinica_id and kv.kit_id=k.id and kv.versao=k.versao_atual),'[]'::jsonb)) order by k.nome) from public.estoque_kits k where k.clinica_id=v_clinica and k.ativo and k.titular_tipo=v_titular and k.titular_dentista_id is not distinct from v_dentista),'[]'::jsonb)));
end; $$;
create function private.listar_usos_atendimento_estoque(p_entrada jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_clinica uuid:=private.estoque_uuid(p_entrada->>'clinicaIdEsperada'); v_atendimento uuid:=private.estoque_uuid(p_entrada->>'atendimentoId'); v_contexto jsonb;
begin
  if jsonb_typeof(p_entrada)<>'object' or not private.estoque_chaves_exatas(p_entrada,array['clinicaIdEsperada','atendimentoId']) or v_clinica is null or v_atendimento is null then return jsonb_build_object('ok',false,'codigo','INVALIDO','mensagem','Consulta de materiais inválida.'); end if;
  v_contexto:=private.estoque_contexto_travado(v_clinica); if (v_contexto->>'ok')::boolean is not true then return v_contexto; end if;
  if not exists(select 1 from public.atendimentos_clinicos a where a.clinica_id=v_clinica and a.id=v_atendimento and a.dentista_id=private.estoque_uuid(v_contexto#>>'{data,dentistaId}')) then return jsonb_build_object('ok',false,'codigo','SEM_ACESSO','mensagem','Atendimento indisponível.'); end if;
  return jsonb_build_object('ok',true,'data',jsonb_build_object('usos',coalesce((select jsonb_agg(jsonb_build_object('usoId',u.id::text,'linhaOrigemId',u.linha_origem_id::text,'revisao',u.revisao,'material',u.snapshot_material,'quantidade',private.estoque_decimal_text(u.quantidade_declarada),'unidade',u.unidade_declarada,'itemId',u.item_id::text,'loteId',u.lote_id::text,'kitVersaoId',case when u.kit_versao_id is null then null else u.kit_versao_id::text end,'estado',u.estado_operacional,'movimentoId',case when u.movimento_id is null then null else u.movimento_id::text end) order by u.created_at,u.id) from public.estoque_usos u where u.clinica_id=v_clinica and u.atendimento_id=v_atendimento and u.autor_usuario_id=auth.uid()),'[]'::jsonb)));
end; $$;
create function public.listar_kits_estoque(p_entrada jsonb) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$ select private.listar_kits_estoque(p_entrada); $$;
create function public.listar_usos_atendimento_estoque(p_entrada jsonb) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$ select private.listar_usos_atendimento_estoque(p_entrada); $$;

-- A confirmação exige aceite exato de cada linha deficitária. Esta prévia só lê os
-- fatos pendentes do próprio dentista; a RPC de confirmação continua recalculando
-- sob lock, portanto ela não transforma a prévia em autoridade de saldo.
create function private.previsualizar_confirmacao_usos_estoque(p_entrada jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_clinica uuid:=private.estoque_uuid(p_entrada->>'clinicaIdEsperada'); v_atendimento uuid:=private.estoque_uuid(p_entrada->>'atendimentoId'); v_contexto jsonb; v_ids uuid[];
begin
  if jsonb_typeof(p_entrada)<>'object' or not private.estoque_chaves_exatas(p_entrada,array['clinicaIdEsperada','atendimentoId','usoIds']) or v_clinica is null or v_atendimento is null or jsonb_typeof(p_entrada->'usoIds')<>'array' or jsonb_array_length(p_entrada->'usoIds') not between 1 and 50 then return jsonb_build_object('ok',false,'codigo','INVALIDO','mensagem','Prévia de materiais inválida.'); end if;
  select array_agg(private.estoque_uuid(value)) into v_ids from jsonb_array_elements_text(p_entrada->'usoIds');
  if array_position(v_ids,null) is not null or cardinality(v_ids)<>cardinality(array(select distinct unnest(v_ids))) then return jsonb_build_object('ok',false,'codigo','INVALIDO','mensagem','Prévia de materiais inválida.'); end if;
  v_contexto:=private.estoque_contexto_travado(v_clinica); if (v_contexto->>'ok')::boolean is not true then return v_contexto; end if;
  if not exists(select 1 from public.atendimentos_clinicos a where a.clinica_id=v_clinica and a.id=v_atendimento and a.dentista_id=private.estoque_uuid(v_contexto#>>'{data,dentistaId}')) then return jsonb_build_object('ok',false,'codigo','SEM_ACESSO','mensagem','Atendimento indisponível.'); end if;
  if (select count(*) from public.estoque_usos u where u.clinica_id=v_clinica and u.atendimento_id=v_atendimento and u.id=any(v_ids) and u.autor_usuario_id=auth.uid() and u.estado_operacional='pendente_autorizacao')<>cardinality(v_ids) then return jsonb_build_object('ok',false,'codigo','CONFLITO','mensagem','Atualize os materiais antes de confirmar.'); end if;
  return jsonb_build_object('ok',true,'data',jsonb_build_object('insuficientes',coalesce((select jsonb_agg(jsonb_build_object('usoId',u.id::text,'versaoItemEsperada',i.versao) order by u.id) from public.estoque_usos u join public.estoque_itens i on i.clinica_id=u.clinica_id and i.id=u.item_id join (select candidato.item_id,candidato.lote_id from public.estoque_usos candidato where candidato.clinica_id=v_clinica and candidato.id=any(v_ids) group by candidato.item_id,candidato.lote_id having coalesce((select sum(m.quantidade) from public.estoque_movimentos m where m.clinica_id=v_clinica and m.item_id=candidato.item_id and m.lote_id=candidato.lote_id),0)-sum(candidato.quantidade_declarada)<0) deficit on deficit.item_id=u.item_id and deficit.lote_id=u.lote_id where u.clinica_id=v_clinica and u.id=any(v_ids)),'[]'::jsonb)));
end; $$;
create function public.previsualizar_confirmacao_usos_estoque(p_entrada jsonb) returns jsonb language sql security invoker set search_path=pg_catalog,public,private as $$ select private.previsualizar_confirmacao_usos_estoque(p_entrada); $$;
revoke all on function private.listar_kits_estoque(jsonb),private.listar_usos_atendimento_estoque(jsonb),private.previsualizar_confirmacao_usos_estoque(jsonb),public.listar_kits_estoque(jsonb),public.listar_usos_atendimento_estoque(jsonb),public.previsualizar_confirmacao_usos_estoque(jsonb) from public,anon,authenticated,service_role;
grant execute on function private.listar_kits_estoque(jsonb),private.listar_usos_atendimento_estoque(jsonb),private.previsualizar_confirmacao_usos_estoque(jsonb),public.listar_kits_estoque(jsonb),public.listar_usos_atendimento_estoque(jsonb),public.previsualizar_confirmacao_usos_estoque(jsonb) to authenticated;
